import { describe, expect, it } from "bun:test";
import { type RequestRow, toRequest } from "./request-row";

describe("toRequest", () => {
	it("preserves zero-valued usage fields when mapping request rows", () => {
		const row: RequestRow = {
			id: "request-1",
			timestamp: 123,
			method: "POST",
			path: "/v1/openai/responses",
			provider: "openai",
			upstream_path: "/responses",
			account_used: "account-1",
			status_code: 200,
			success: 1,
			error_message: null,
			response_time_ms: 0,
			failover_attempts: 0,
			model: "gpt-4o-mini",
			prompt_tokens: 0,
			completion_tokens: 0,
			total_tokens: 0,
			cost_usd: 0,
			input_tokens: 0,
			cache_read_input_tokens: 0,
			cache_creation_input_tokens: 0,
			output_tokens: 0,
			reasoning_tokens: 0,
			output_tokens_per_second: 0,
			ttft_ms: 0,
			proxy_overhead_ms: 0,
			upstream_ttfb_ms: 0,
			streaming_duration_ms: 0,
			response_id: "resp-1",
			previous_response_id: null,
			response_chain_id: "resp-1",
			client_session_id: "session-1",
		};

		expect(toRequest(row)).toEqual({
			id: "request-1",
			timestamp: 123,
			method: "POST",
			path: "/v1/openai/responses",
			provider: "openai",
			upstreamPath: "/responses",
			accountUsed: "account-1",
			statusCode: 200,
			success: true,
			errorMessage: null,
			responseTimeMs: 0,
			failoverAttempts: 0,
			model: "gpt-4o-mini",
			promptTokens: 0,
			completionTokens: 0,
			totalTokens: 0,
			costUsd: 0,
			inputTokens: 0,
			cacheReadInputTokens: 0,
			cacheCreationInputTokens: 0,
			outputTokens: 0,
			reasoningTokens: 0,
			tokensPerSecond: 0,
			ttftMs: 0,
			proxyOverheadMs: 0,
			upstreamTtfbMs: 0,
			streamingDurationMs: 0,
			responseId: "resp-1",
			previousResponseId: null,
			responseChainId: "resp-1",
			clientSessionId: "session-1",
		});
	});

	it("keeps in-flight request rows distinct from failed requests", () => {
		const row: RequestRow = {
			id: "request-pending",
			timestamp: 456,
			method: "POST",
			path: "/v1/openai/responses",
			provider: "openai",
			upstream_path: "/responses",
			account_used: null,
			status_code: 200,
			success: null,
			error_message: null,
			response_time_ms: null,
			failover_attempts: 0,
			model: null,
			prompt_tokens: null,
			completion_tokens: null,
			total_tokens: null,
			cost_usd: null,
			input_tokens: null,
			cache_read_input_tokens: null,
			cache_creation_input_tokens: null,
			output_tokens: null,
			reasoning_tokens: null,
			output_tokens_per_second: null,
			ttft_ms: null,
			proxy_overhead_ms: null,
			upstream_ttfb_ms: null,
			streaming_duration_ms: null,
			response_id: null,
			previous_response_id: null,
			response_chain_id: null,
			client_session_id: null,
		};

		expect(toRequest(row)).toEqual({
			id: "request-pending",
			timestamp: 456,
			method: "POST",
			path: "/v1/openai/responses",
			provider: "openai",
			upstreamPath: "/responses",
			accountUsed: null,
			statusCode: 200,
			success: null,
			errorMessage: null,
			responseTimeMs: null,
			failoverAttempts: 0,
			model: null,
			promptTokens: null,
			completionTokens: null,
			totalTokens: null,
			costUsd: null,
			inputTokens: null,
			cacheReadInputTokens: null,
			cacheCreationInputTokens: null,
			outputTokens: null,
			reasoningTokens: null,
			tokensPerSecond: null,
			ttftMs: null,
			proxyOverheadMs: null,
			upstreamTtfbMs: null,
			streamingDurationMs: null,
			responseId: null,
			previousResponseId: null,
			responseChainId: null,
			clientSessionId: null,
		});
	});
});
