#!/usr/bin/env bun
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface Platform {
	target: string;
	outfile: string;
	description: string;
}

// Get project root directory (two levels up from this script)
const projectRoot = join(import.meta.dir, "../..");

const platforms: Platform[] = [
	{
		target: "bun-linux-amd64",
		outfile: "better-ccflare-linux-amd64",
		description: "Linux x86_64",
	},
	{
		target: "bun-linux-arm64",
		outfile: "better-ccflare-linux-arm64",
		description: "Linux ARM64",
	},
	{
		target: "bun-darwin-x64",
		outfile: "better-ccflare-macos-x86_64",
		description: "macOS Intel",
	},
	{
		target: "bun-darwin-arm64",
		outfile: "better-ccflare-macos-arm64",
		description: "macOS Apple Silicon",
	},
	{
		target: "bun-windows-x64",
		outfile: "better-ccflare-windows-x64.exe",
		description: "Windows x86_64",
	},
];

async function buildWorker() {
	console.log("🔨 Building workers...");

	// Write empty placeholders so imports resolve before workers are built
	const inlineVacuumWorkerPlaceholderPath = join(
		projectRoot,
		"packages/database/src/inline-vacuum-worker.ts",
	);
	if (!existsSync(inlineVacuumWorkerPlaceholderPath)) {
		writeFileSync(
			inlineVacuumWorkerPlaceholderPath,
			`// Auto-generated by apps/cli build step. Do not edit manually.\nexport const EMBEDDED_VACUUM_WORKER_CODE = "";`,
		);
	}

	// Write empty inline-integrity-check-worker.ts placeholder
	const inlineIntegrityCheckWorkerPlaceholderPath = join(
		projectRoot,
		"packages/database/src/inline-integrity-check-worker.ts",
	);
	if (!existsSync(inlineIntegrityCheckWorkerPlaceholderPath)) {
		writeFileSync(
			inlineIntegrityCheckWorkerPlaceholderPath,
			`// Auto-generated by apps/cli build step. Do not edit manually.\nexport const EMBEDDED_INTEGRITY_CHECK_WORKER_CODE = "";`,
		);
	}

	// Write empty inline-incremental-vacuum-worker.ts placeholder so imports resolve before workers are built.
	const inlineIncVacuumWorkerPlaceholderPath = join(
		projectRoot,
		"packages/database/src/inline-incremental-vacuum-worker.ts",
	);
	if (!existsSync(inlineIncVacuumWorkerPlaceholderPath)) {
		writeFileSync(
			inlineIncVacuumWorkerPlaceholderPath,
			`// Auto-generated by apps/cli build step. Do not edit manually.\nexport const EMBEDDED_INCREMENTAL_VACUUM_WORKER_CODE = "";`,
		);
	}

	// Build vacuum worker
	execSync(
		`bun build ../../packages/database/src/vacuum-worker.ts --outfile dist/vacuum-worker.js --target=bun --minify`,
		{ stdio: "inherit" },
	);

	// Encode vacuum worker
	const vacuumWorkerCode = await Bun.file("dist/vacuum-worker.js").text();
	const vacuumEncoded = Buffer.from(vacuumWorkerCode).toString("base64");

	// Write inline vacuum worker
	const inlineVacuumWorkerPath = join(
		projectRoot,
		"packages/database/src/inline-vacuum-worker.ts",
	);
	writeFileSync(
		inlineVacuumWorkerPath,
		`// Auto-generated by apps/cli build step. Do not edit manually.\nexport const EMBEDDED_VACUUM_WORKER_CODE = "${vacuumEncoded}";`,
	);

	// Build integrity-check worker
	execSync(
		`bun build ../../packages/database/src/integrity-check-worker.ts --outfile dist/integrity-check-worker.js --target=bun --minify`,
		{ stdio: "inherit" },
	);

	// Encode integrity-check worker
	const integrityCheckWorkerCode = await Bun.file(
		"dist/integrity-check-worker.js",
	).text();
	const integrityCheckEncoded = Buffer.from(integrityCheckWorkerCode).toString(
		"base64",
	);

	// Write inline integrity-check worker
	const inlineIntegrityCheckWorkerPath = join(
		projectRoot,
		"packages/database/src/inline-integrity-check-worker.ts",
	);
	writeFileSync(
		inlineIntegrityCheckWorkerPath,
		`// Auto-generated by apps/cli build step. Do not edit manually.\nexport const EMBEDDED_INTEGRITY_CHECK_WORKER_CODE = "${integrityCheckEncoded}";`,
	);

	// Build incremental-vacuum worker
	execSync(
		`bun build ../../packages/database/src/incremental-vacuum-worker.ts --outfile dist/incremental-vacuum-worker.js --target=bun --minify`,
		{ stdio: "inherit" },
	);

	// Encode incremental-vacuum worker
	const incVacuumWorkerCode = await Bun.file(
		"dist/incremental-vacuum-worker.js",
	).text();
	const incVacuumEncoded = Buffer.from(incVacuumWorkerCode).toString("base64");

	// Write inline incremental-vacuum worker
	const inlineIncVacuumWorkerPath = join(
		projectRoot,
		"packages/database/src/inline-incremental-vacuum-worker.ts",
	);
	writeFileSync(
		inlineIncVacuumWorkerPath,
		`// Auto-generated by apps/cli build step. Do not edit manually.\nexport const EMBEDDED_INCREMENTAL_VACUUM_WORKER_CODE = "${incVacuumEncoded}";`,
	);

	console.log("✅ Workers built and encoded\n");
}

async function buildPlatform(platform: Platform) {
	console.log(`🏗️  Building for ${platform.description}...`);

	// Get version from package.json
	const packageJson = await Bun.file("./package.json").json();
	const version = packageJson.version;

	const buildCmd = [
		"bun build src/main.ts",
		"--compile",
		`--outfile dist/${platform.outfile}`,
		`--target=${platform.target}`,
		"--minify",
		`--define __BETTER_CCFLARE_VERSION__='"${version}"'`,
	].join(" ");

	try {
		execSync(buildCmd, { stdio: "inherit" });
		console.log(`✅ ${platform.description} build complete\n`);
	} catch (error) {
		console.error(`❌ Failed to build for ${platform.description}`);
		throw error;
	}
}

async function main() {
	console.log("🚀 Starting multi-architecture build...\n");

	// Create dist directory
	mkdirSync("dist", { recursive: true });

	// Build worker first
	await buildWorker();

	// Build for all platforms
	for (const platform of platforms) {
		await buildPlatform(platform);
	}

	console.log("🎉 All builds completed successfully!");
	console.log("\n📦 Built binaries:");
	for (const platform of platforms) {
		console.log(`   - dist/${platform.outfile} (${platform.description})`);
	}
}

main().catch((error) => {
	console.error("Build failed:", error);
	process.exit(1);
});
